-- ============================================================================
-- AGRODATA - Backup & Restore support
-- ----------------------------------------------------------------------------
-- 1. Switch identity columns to GENERATED BY DEFAULT so a restore can re-insert
--    rows with their original primary keys (preserving relationships).
-- 2. Provide resync_identity_sequences() to advance sequences after a restore
--    so new inserts don't collide with restored IDs.
-- ============================================================================

alter table public.user_roles        alter column role_id     set generated by default;
alter table public.users             alter column user_id     set generated by default;
alter table public.farmers           alter column farmer_id   set generated by default;
alter table public.farms             alter column farm_id     set generated by default;
alter table public.farm_plots        alter column plot_id     set generated by default;
alter table public.crops             alter column crop_id     set generated by default;
alter table public.planting_records  alter column planting_id set generated by default;
alter table public.harvest_inventory alter column inventory_id set generated by default;
alter table public.yield_statistics  alter column stat_id     set generated by default;
alter table public.audit_logs        alter column log_id      set generated by default;

create or replace function public.resync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  cols text[][] := array[
    array['user_roles','role_id'],
    array['users','user_id'],
    array['farmers','farmer_id'],
    array['farms','farm_id'],
    array['farm_plots','plot_id'],
    array['crops','crop_id'],
    array['planting_records','planting_id'],
    array['harvest_inventory','inventory_id'],
    array['yield_statistics','stat_id'],
    array['audit_logs','log_id']
  ];
  c text[];
  seq text;
  maxid bigint;
begin
  foreach c slice 1 in array cols loop
    seq := pg_get_serial_sequence('public.' || c[1], c[2]);
    execute format('select max(%I) from public.%I', c[2], c[1]) into maxid;
    perform setval(seq, coalesce(maxid, 1), maxid is not null);
  end loop;
end $$;

grant execute on function public.resync_identity_sequences() to authenticated;
