-- ============================================================================
-- AGRODATA - Backup & Restore support for the livestock/fisheries expansion
-- ----------------------------------------------------------------------------
-- Migration 0005 prepared the crop-era tables for restore but predates the
-- sector tables added in 0006/0007. Those tables are GENERATED ALWAYS, so a
-- restore that re-inserts original primary keys would be rejected by Postgres.
-- This migration:
--   1. Switches the sector identity columns to GENERATED BY DEFAULT.
--   2. Extends resync_identity_sequences() to cover them.
-- ============================================================================

alter table public.livestock_species    alter column species_id    set generated by default;
alter table public.livestock_records    alter column record_id     set generated by default;
alter table public.fisherfolk           alter column fisherfolk_id set generated by default;
alter table public.fish_catch           alter column catch_id      set generated by default;
alter table public.aquaculture_sites    alter column site_id       set generated by default;
alter table public.aquaculture_cycles   alter column cycle_id      set generated by default;
alter table public.livestock_statistics alter column stat_id       set generated by default;
alter table public.fisheries_statistics alter column stat_id       set generated by default;

create or replace function public.resync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  cols text[][] := array[
    array['user_roles','role_id'],
    array['users','user_id'],
    array['farmers','farmer_id'],
    array['farms','farm_id'],
    array['farm_plots','plot_id'],
    array['crops','crop_id'],
    array['planting_records','planting_id'],
    array['harvest_inventory','inventory_id'],
    array['yield_statistics','stat_id'],
    array['audit_logs','log_id'],
    -- Livestock & poultry, fisheries, and aquaculture (migrations 0006-0007)
    array['livestock_species','species_id'],
    array['livestock_records','record_id'],
    array['fisherfolk','fisherfolk_id'],
    array['fish_catch','catch_id'],
    array['aquaculture_sites','site_id'],
    array['aquaculture_cycles','cycle_id'],
    array['livestock_statistics','stat_id'],
    array['fisheries_statistics','stat_id']
  ];
  c text[];
  seq text;
  maxid bigint;
begin
  foreach c slice 1 in array cols loop
    seq := pg_get_serial_sequence('public.' || c[1], c[2]);
    execute format('select max(%I) from public.%I', c[2], c[1]) into maxid;
    perform setval(seq, coalesce(maxid, 1), maxid is not null);
  end loop;
end $$;

grant execute on function public.resync_identity_sequences() to authenticated;
