-- ============================================================================
-- AGRODATA - Aquaculture statistical summaries
-- ----------------------------------------------------------------------------
-- Adds `aquaculture_statistics`, mirroring the crop/livestock/fisheries stored
-- summaries. Rows are computed and persisted server-side by the
-- `compute-statistics` Edge Function, grouped by cultured species, site type,
-- unit, and reporting period.
--
-- This migration is ADDITIVE and non-destructive: it only creates a new table,
-- its policies/indexes, and extends the sequence-resync helper. No existing
-- table, column, policy, or data is dropped or altered destructively.
--
-- Unit awareness: aquaculture quantities are recorded with a free-text unit, so
-- summaries are grouped by `unit` and never sum quantities across units.
-- ============================================================================

create table if not exists public.aquaculture_statistics (
  -- GENERATED BY DEFAULT (not ALWAYS) so Backup & Restore can re-insert rows
  -- with their original primary keys, consistent with the other sector tables.
  stat_id          bigint generated by default as identity primary key,
  species_name     varchar(100) not null,
  site_type        aqua_site_type,
  unit             varchar(50) not null default 'kg',
  period_type      period_type not null,
  period_start     date not null,
  period_end       date not null,
  total_stocked    numeric(12,2),
  total_harvested  numeric(12,2),
  active_cycles    int,      -- cycles still STOCKED in the period
  harvested_cycles int,      -- cycles marked HARVESTED in the period
  lost_cycles      int,      -- cycles marked LOST in the period
  computed_at      timestamptz not null default now()
);

-- ---------- Indexes ----------------------------------------------------------
create index if not exists idx_aqua_stats_period  on public.aquaculture_statistics (period_start);
create index if not exists idx_aqua_stats_species on public.aquaculture_statistics (species_name);

-- ---------- Row Level Security ----------------------------------------------
-- Matches migration 0009: any signed-in user with an ACTIVE OMA profile may
-- read/write. (Recomputation is additionally admin-gated in the Edge Function.)
alter table public.aquaculture_statistics enable row level security;

drop policy if exists "auth_read_aquaculture_statistics"   on public.aquaculture_statistics;
drop policy if exists "auth_insert_aquaculture_statistics" on public.aquaculture_statistics;
drop policy if exists "auth_update_aquaculture_statistics" on public.aquaculture_statistics;
drop policy if exists "auth_delete_aquaculture_statistics" on public.aquaculture_statistics;

create policy "auth_read_aquaculture_statistics"
  on public.aquaculture_statistics for select using (public.has_active_profile());
create policy "auth_insert_aquaculture_statistics"
  on public.aquaculture_statistics for insert with check (public.has_active_profile());
create policy "auth_update_aquaculture_statistics"
  on public.aquaculture_statistics for update using (public.has_active_profile());
create policy "auth_delete_aquaculture_statistics"
  on public.aquaculture_statistics for delete using (public.has_active_profile());

-- ---------- Extend the sequence-resync helper -------------------------------
-- Re-create the function including the new table. This preserves the migration
-- 0010 hardening: SECURITY DEFINER, fixed search_path, an internal admin check,
-- and the anon/PUBLIC revoke below.
create or replace function public.resync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  cols text[][] := array[
    array['user_roles','role_id'],
    array['users','user_id'],
    array['farmers','farmer_id'],
    array['farms','farm_id'],
    array['farm_plots','plot_id'],
    array['crops','crop_id'],
    array['planting_records','planting_id'],
    array['harvest_inventory','inventory_id'],
    array['yield_statistics','stat_id'],
    array['audit_logs','log_id'],
    array['livestock_species','species_id'],
    array['livestock_records','record_id'],
    array['fisherfolk','fisherfolk_id'],
    array['fish_catch','catch_id'],
    array['aquaculture_sites','site_id'],
    array['aquaculture_cycles','cycle_id'],
    array['livestock_statistics','stat_id'],
    array['fisheries_statistics','stat_id'],
    array['aquaculture_statistics','stat_id']
  ];
  c text[];
  seq text;
  maxid bigint;
begin
  if not public.is_admin() then
    raise exception 'Only the Municipal Agriculturalist may resync identity sequences.'
      using errcode = '42501';
  end if;

  foreach c slice 1 in array cols loop
    seq := pg_get_serial_sequence('public.' || c[1], c[2]);
    execute format('select max(%I) from public.%I', c[2], c[1]) into maxid;
    perform setval(seq, coalesce(maxid, 1), maxid is not null);
  end loop;
end $$;

revoke all on function public.resync_identity_sequences() from public, anon;
grant execute on function public.resync_identity_sequences() to authenticated;
