-- ============================================================================
-- AGRODATA - Controlled reference catalogs: measurement units & aquatic species
-- ----------------------------------------------------------------------------
-- Replaces free-text units and fish/aquatic species with managed reference
-- lists so summaries and reports aggregate consistently. Managing reference
-- data is a Municipal Agriculturalist task, so writes are admin-only while any
-- active OMA profile may read.
--
-- Additive and non-destructive: existing free-text values in fish_catch /
-- aquaculture_cycles / livestock_records are left untouched. The catalogs are
-- used by the UI going forward; the edit forms keep any legacy value that is
-- not yet in the catalog so no data is lost.
-- ============================================================================

-- ---------- Measurement units ------------------------------------------------
create table if not exists public.measurement_units (
  unit_id    bigint generated by default as identity primary key,
  unit_name  varchar(50) not null unique,
  dimension  varchar(20),   -- WEIGHT | COUNT | VOLUME | AREA (informational)
  active     boolean not null default true
);

-- ---------- Aquatic species --------------------------------------------------
create table if not exists public.aquatic_species (
  aqua_species_id bigint generated by default as identity primary key,
  common_name     varchar(100) not null unique,
  scientific_name varchar(150),
  active          boolean not null default true
);

-- ---------- Indexes ----------------------------------------------------------
create index if not exists idx_units_active   on public.measurement_units (active);
create index if not exists idx_aqua_sp_active on public.aquatic_species (active);

-- ---------- Row Level Security ----------------------------------------------
-- Read: any signed-in user with an ACTIVE profile. Write: admin only.
alter table public.measurement_units enable row level security;
alter table public.aquatic_species   enable row level security;

do $$
declare
  t text;
  ref_tables text[] := array['measurement_units', 'aquatic_species'];
begin
  foreach t in array ref_tables loop
    execute format('drop policy if exists "read_%1$s"   on public.%1$s;', t);
    execute format('drop policy if exists "admin_ins_%1$s" on public.%1$s;', t);
    execute format('drop policy if exists "admin_upd_%1$s" on public.%1$s;', t);
    execute format('drop policy if exists "admin_del_%1$s" on public.%1$s;', t);

    execute format(
      'create policy "read_%1$s" on public.%1$s for select using (public.has_active_profile());', t);
    execute format(
      'create policy "admin_ins_%1$s" on public.%1$s for insert with check (public.is_admin());', t);
    execute format(
      'create policy "admin_upd_%1$s" on public.%1$s for update using (public.is_admin());', t);
    execute format(
      'create policy "admin_del_%1$s" on public.%1$s for delete using (public.is_admin());', t);
  end loop;
end $$;

-- ---------- Seed defaults (editable by the Municipal Agriculturalist) --------
insert into public.measurement_units (unit_name, dimension) values
  ('kg', 'WEIGHT'), ('g', 'WEIGHT'), ('MT', 'WEIGHT'), ('sack', 'WEIGHT'),
  ('pcs', 'COUNT'), ('tray', 'COUNT'), ('head', 'COUNT'), ('bundle', 'COUNT'),
  ('L', 'VOLUME'), ('mL', 'VOLUME'),
  ('hectare', 'AREA')
on conflict (unit_name) do nothing;

insert into public.aquatic_species (common_name, scientific_name) values
  ('Tilapia', 'Oreochromis niloticus'),
  ('Milkfish (Bangus)', 'Chanos chanos'),
  ('Shrimp', null),
  ('Prawn', null),
  ('Mud Crab (Alimango)', 'Scylla serrata'),
  ('Blue Crab (Alimasag)', 'Portunus pelagicus'),
  ('Grouper (Lapu-lapu)', null),
  ('Tuna', null),
  ('Sardines (Tamban)', null),
  ('Mackerel (Alumahan)', null),
  ('Squid (Pusit)', null),
  ('Seaweed', null)
on conflict (common_name) do nothing;

-- ---------- Extend the sequence-resync helper -------------------------------
-- Preserves the migration 0010 hardening (admin check + fixed search_path)
-- and adds the two new catalog tables.
create or replace function public.resync_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  cols text[][] := array[
    array['user_roles','role_id'],
    array['users','user_id'],
    array['farmers','farmer_id'],
    array['farms','farm_id'],
    array['farm_plots','plot_id'],
    array['crops','crop_id'],
    array['planting_records','planting_id'],
    array['harvest_inventory','inventory_id'],
    array['yield_statistics','stat_id'],
    array['audit_logs','log_id'],
    array['livestock_species','species_id'],
    array['livestock_records','record_id'],
    array['fisherfolk','fisherfolk_id'],
    array['fish_catch','catch_id'],
    array['aquaculture_sites','site_id'],
    array['aquaculture_cycles','cycle_id'],
    array['livestock_statistics','stat_id'],
    array['fisheries_statistics','stat_id'],
    array['aquaculture_statistics','stat_id'],
    array['measurement_units','unit_id'],
    array['aquatic_species','aqua_species_id']
  ];
  c text[];
  seq text;
  maxid bigint;
begin
  if not public.is_admin() then
    raise exception 'Only the Municipal Agriculturalist may resync identity sequences.'
      using errcode = '42501';
  end if;

  foreach c slice 1 in array cols loop
    seq := pg_get_serial_sequence('public.' || c[1], c[2]);
    execute format('select max(%I) from public.%I', c[2], c[1]) into maxid;
    perform setval(seq, coalesce(maxid, 1), maxid is not null);
  end loop;
end $$;

revoke all on function public.resync_identity_sequences() from public, anon;
grant execute on function public.resync_identity_sequences() to authenticated;
